# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
podfile: Example/Podfile
before_install:
- gem install xcodeproj -v '~> 0.23.1' --no-ri --no-rdoc
- gem install cocoapods --no-ri --no-rdoc # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xctool test -workspace Example/YWeatherAPI.xcworkspace -scheme YWeatherAPI-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick --allow-warnings
